resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/macdonda/concourse-test.git
    branch: master
jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - task: package
    privileged: true
    file: source-code/ci/tasks/package.yml
